import { Listing } from '@/types'

export const mockListings: Listing[] = [
  {
    id: '1',
    userId: 'user1',
    title: 'AI-Powered Content Generator SaaS',
    tagline: 'Generate high-quality content with GPT-4',
    description: 'A fully functional SaaS platform that helps businesses generate blog posts, social media content, and marketing copy using AI. Built with modern tech stack and ready to scale.',
    category: 'AI_ML',
    techStack: {
      frontend: ['Next.js', 'React', 'Tailwind CSS', 'shadcn/ui'],
      backend: ['Node.js', 'Fastify', 'Prisma'],
      database: ['PostgreSQL', 'Redis'],
      infrastructure: ['Vercel', 'Railway', 'AWS S3'],
      services: ['OpenAI', 'Stripe', 'Clerk'],
    },
    price: 75000,
    currency: 'USD',
    priceNegotiable: true,
    metrics: {
      mrr: 3500,
      arr: 42000,
      users: {
        total: 450,
        active: 280,
        growth: 15,
      },
      revenue: {
        total: 52000,
        monthly: [2000, 2500, 3000, 3200, 3500, 3800],
      },
      costs: {
        hosting: 250,
        other: 800,
      },
      traffic: {
        monthly: 12000,
        sources: {
          organic: 6000,
          paid: 4000,
          referral: 2000,
        },
      },
      churn: 5,
      ltv: 850,
      cac: 120,
    },
    status: 'ACTIVE',
    visibility: 'public',
    featured: true,
    slug: 'ai-content-generator-saas',
    thumbnailUrl: undefined,
    images: [],
    demoUrl: 'https://demo.example.com',
    views: 1250,
    favorites: 45,
    inquiries: 12,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-20'),
    publishedAt: new Date('2024-03-16'),
  },
  {
    id: '2',
    userId: 'user2',
    title: 'E-Commerce Analytics Dashboard',
    tagline: 'Real-time analytics for online stores',
    description: 'Comprehensive analytics platform for e-commerce businesses. Track sales, customer behavior, inventory, and more. Integrates with Shopify, WooCommerce, and custom stores.',
    category: 'SAAS',
    techStack: {
      frontend: ['React', 'Vue.js', 'Tailwind CSS'],
      backend: ['Python', 'FastAPI'],
      database: ['PostgreSQL', 'MongoDB'],
      infrastructure: ['AWS', 'Docker'],
      services: ['Stripe', 'SendGrid'],
    },
    price: 120000,
    currency: 'USD',
    priceNegotiable: false,
    metrics: {
      mrr: 8500,
      arr: 102000,
      users: {
        total: 850,
        active: 620,
        growth: 22,
      },
      revenue: {
        total: 145000,
        monthly: [6000, 7000, 7500, 8000, 8500, 9000],
      },
      costs: {
        hosting: 450,
        other: 1200,
      },
      traffic: {
        monthly: 25000,
        sources: {
          organic: 15000,
          paid: 7000,
          referral: 3000,
        },
      },
      churn: 3,
      ltv: 1850,
      cac: 180,
    },
    status: 'ACTIVE',
    visibility: 'public',
    featured: true,
    slug: 'ecommerce-analytics-dashboard',
    thumbnailUrl: undefined,
    images: [],
    demoUrl: 'https://demo.analytics.example.com',
    views: 2100,
    favorites: 78,
    inquiries: 23,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-18'),
    publishedAt: new Date('2024-03-11'),
  },
  {
    id: '3',
    userId: 'user3',
    title: 'NFT Marketplace Platform',
    tagline: 'Buy, sell, and trade digital collectibles',
    description: 'Full-featured NFT marketplace with wallet integration, auction system, and creator tools. Built on Ethereum with low gas fees optimization.',
    category: 'WEB3',
    techStack: {
      frontend: ['Next.js', 'React', 'Tailwind CSS'],
      backend: ['Node.js', 'Express'],
      database: ['MongoDB', 'IPFS'],
      infrastructure: ['Vercel', 'AWS'],
      services: ['Web3.js', 'Ethers.js', 'Stripe'],
    },
    price: 250000,
    currency: 'USD',
    priceNegotiable: true,
    metrics: {
      mrr: 15000,
      arr: 180000,
      users: {
        total: 3200,
        active: 1800,
        growth: 35,
      },
      revenue: {
        total: 320000,
        monthly: [10000, 12000, 13000, 14000, 15000, 16000],
      },
      costs: {
        hosting: 800,
        other: 2000,
      },
      traffic: {
        monthly: 85000,
        sources: {
          organic: 45000,
          paid: 25000,
          referral: 15000,
        },
      },
      churn: 8,
      ltv: 2500,
      cac: 250,
    },
    status: 'ACTIVE',
    visibility: 'public',
    featured: false,
    slug: 'nft-marketplace-platform',
    thumbnailUrl: undefined,
    images: [],
    demoUrl: 'https://nft.example.com',
    views: 3500,
    favorites: 125,
    inquiries: 45,
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-19'),
    publishedAt: new Date('2024-03-06'),
  },
  {
    id: '4',
    userId: 'user4',
    title: 'Fitness Tracking Mobile App',
    tagline: 'Track workouts, nutrition, and progress',
    description: 'Cross-platform mobile app for fitness enthusiasts. Features include workout plans, nutrition tracking, progress photos, and social features.',
    category: 'HEALTHTECH',
    techStack: {
      frontend: ['React Native', 'Expo'],
      backend: ['Node.js', 'Fastify'],
      database: ['PostgreSQL', 'Redis'],
      infrastructure: ['Railway', 'AWS S3'],
      services: ['Stripe', 'Clerk', 'Resend'],
    },
    price: 45000,
    currency: 'USD',
    priceNegotiable: true,
    metrics: {
      mrr: 2200,
      arr: 26400,
      users: {
        total: 1200,
        active: 850,
        growth: 18,
      },
      revenue: {
        total: 35000,
        monthly: [1500, 1700, 1900, 2000, 2200, 2400],
      },
      costs: {
        hosting: 150,
        other: 400,
      },
      traffic: {
        monthly: 8000,
        sources: {
          organic: 4000,
          paid: 2500,
          referral: 1500,
        },
      },
      churn: 6,
      ltv: 450,
      cac: 85,
    },
    status: 'ACTIVE',
    visibility: 'public',
    featured: false,
    slug: 'fitness-tracking-mobile-app',
    thumbnailUrl: undefined,
    images: [],
    views: 890,
    favorites: 32,
    inquiries: 8,
    createdAt: new Date('2024-03-12'),
    updatedAt: new Date('2024-03-17'),
    publishedAt: new Date('2024-03-13'),
  },
  {
    id: '5',
    userId: 'user5',
    title: 'AI Resume Builder',
    tagline: 'Create professional resumes with AI assistance',
    description: 'AI-powered resume builder that helps job seekers create ATS-friendly resumes. Includes templates, AI suggestions, and export options.',
    category: 'AI_ML',
    techStack: {
      frontend: ['Next.js', 'React', 'Tailwind CSS'],
      backend: ['Python', 'FastAPI'],
      database: ['PostgreSQL'],
      infrastructure: ['Vercel', 'Railway'],
      services: ['OpenAI', 'Stripe'],
    },
    price: 28000,
    currency: 'USD',
    priceNegotiable: false,
    metrics: {
      mrr: 1800,
      arr: 21600,
      users: {
        total: 650,
        active: 420,
        growth: 12,
      },
      revenue: {
        total: 28000,
        monthly: [1200, 1400, 1500, 1600, 1800, 1900],
      },
      costs: {
        hosting: 120,
        other: 350,
      },
      traffic: {
        monthly: 15000,
        sources: {
          organic: 9000,
          paid: 4000,
          referral: 2000,
        },
      },
      churn: 4,
      ltv: 380,
      cac: 65,
    },
    status: 'ACTIVE',
    visibility: 'public',
    featured: false,
    slug: 'ai-resume-builder',
    thumbnailUrl: undefined,
    images: [],
    demoUrl: 'https://resume.example.com',
    views: 1450,
    favorites: 56,
    inquiries: 15,
    createdAt: new Date('2024-03-08'),
    updatedAt: new Date('2024-03-16'),
    publishedAt: new Date('2024-03-09'),
  },
  {
    id: '6',
    userId: 'user6',
    title: 'Payment Gateway for Crypto',
    tagline: 'Accept crypto payments easily',
    description: 'Simple payment gateway that allows businesses to accept cryptocurrency payments. Supports Bitcoin, Ethereum, and major stablecoins.',
    category: 'FINTECH',
    techStack: {
      frontend: ['React', 'Next.js'],
      backend: ['Go', 'Node.js'],
      database: ['PostgreSQL', 'Redis'],
      infrastructure: ['AWS', 'Docker'],
      services: ['Web3.js', 'Stripe'],
    },
    price: 180000,
    currency: 'USD',
    priceNegotiable: true,
    metrics: {
      mrr: 12000,
      arr: 144000,
      users: {
        total: 450,
        active: 320,
        growth: 25,
      },
      revenue: {
        total: 185000,
        monthly: [8000, 9000, 10000, 11000, 12000, 13000],
      },
      costs: {
        hosting: 600,
        other: 1500,
      },
      traffic: {
        monthly: 18000,
        sources: {
          organic: 8000,
          paid: 7000,
          referral: 3000,
        },
      },
      churn: 2,
      ltv: 3200,
      cac: 280,
    },
    status: 'ACTIVE',
    visibility: 'public',
    featured: true,
    slug: 'crypto-payment-gateway',
    thumbnailUrl: undefined,
    images: [],
    demoUrl: 'https://cryptopay.example.com',
    views: 2800,
    favorites: 95,
    inquiries: 34,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-20'),
    publishedAt: new Date('2024-03-02'),
  },
]
